name: flutter_radio_player
description: Flutter radio plugin handles a single streaming audio preciously.
version: 1.0.7
homepage: https://github.com/Sithira/FlutterRadioPlayer

environment:
  sdk: '>=2.17.6 <3.0.0'
  flutter: ">=2.0.0 <3.0.5"

dependencies:
  flutter:
    sdk: flutter
  flutter_plugin_android_lifecycle: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: me.sithiramunasinghe.flutter.flutter_radio_player
        pluginClass: FlutterRadioPlayerPlugin
      ios:
        pluginClass: FlutterRadioPlayerPlugin
